name: 'test'

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'where to look for a release'
        required: true
        default: manjaro-sway/manjaro-sway-settings-git
      release: 
        description: 'release to download'
        required: true
        default: r1841.a635ef1c-2
      branch:
        description: 'manjaro lifecycle branch'
        default: 'testing'
        type: choice
        options:
        - stable
        - testing
        - unstable
  push:      
    branches:
      - main

## fallbacks only needed for push-events
env:
  repository: ${{ inputs.repository || 'manjaro-sway/manjaro-sway-settings-git' }}
  release: ${{ inputs.release || 'r1841.a635ef1c-2' }}
  branch: ${{ inputs.branch || 'testing' }}

concurrency:
  ## fallbacks only needed for push-events
  group: ${{ inputs.repository || 'manjaro-sway/manjaro-sway-settings-git' }}-${{ inputs.branch || 'testing' }}
  cancel-in-progress: true

jobs:
  repo-add:
    ## fallbacks only needed for push-events
    name: add  ${{ inputs.repository || 'manjaro-sway/manjaro-sway-settings-git' }}@${{ inputs.release || 'r1841.a635ef1c-2' }} to ${{ inputs.branch || 'testing' }}
    runs-on: ubuntu-latest
    container: docker://archlinux:base
    permissions:
      contents: write
    steps:
      - name: install tools
        shell: bash
        run: |
          pacman -Sy --noconfirm --needed git git-lfs github-cli
      # needed only to fetch the action.yml
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 1
      - id: repo-add
        uses: ./
        with:
          repository: ${{ env.repository }}
          release: ${{ env.release }}
          branch: ${{ env.branch }}
